---
title: "ggmap tutorial"
output: html_notebook
---

测试使用ggmap绘图工具. 参考网站:

* [Getting started: Stamen maps with ggmap](https://statisticaloddsandends.wordpress.com/2018/10/25/getting-started-stamen-maps-with-ggmap/)

# 载入工具

```{r, message=FALSE, warning=FALSE}
library(dkMetIO)
library(ggplot2)
library(ggmap)
```

# 读入站点观测数据

```{r}
obs <- retrieve_micaps_station_data("SURFACE/PLOT_NATIONAL/", filename="20190419200000.000")
head(obs)
```

```{r}
ggplot() +
  geom_point(data=obs, mapping = aes(x=lon, y=lat, col=temp))+
  scale_color_distiller(palette = "YlOrRd", direction = 1)
```

由于使用google地图需要API账号，所以一般使用[stamen地图](http://maps.stamen.com/)或[OpenStreetMap](https://www.openstreetmap.org/)

```{r, warning=FALSE, message=FALSE, fig.width=8, fig.height=8}
mbox <- c(left = 116, bottom = 39.6, right = 116.8, top = 40.2)
map <- get_stamenmap(mbox, zoom=10, maptype = "toner")

ggmap(map) + 
  geom_point(data=obs, mapping = aes(x=lon, y=lat, col=temp, size=2))+
  scale_color_distiller(palette = "Paired", direction = 1, limit=c(12,17))
```
```{r, warning=FALSE, message=FALSE, fig.width=8, fig.height=8}
mbox <- c(left = 116, bottom = 39.6, right = 116.8, top = 40.2)
map <- get_stamenmap(mbox, zoom=10, maptype = "watercolor")

ggmap(map) + 
  geom_point(data=obs, mapping = aes(x=lon, y=lat, col=temp, size=2))+
  scale_color_distiller(palette = "Paired", direction = 1, limit=c(12,17))
```

```{r, warning=FALSE, message=FALSE, fig.width=8, fig.height=8}
mbox <- c(left = 116, bottom = 39.6, right = 116.8, top = 40.2)
map <- get_stamenmap(mbox, zoom=10, maptype = "terrain")

ggmap(map) + 
  geom_point(data=obs, mapping = aes(x=lon, y=lat, col=temp, size=2))+
  scale_color_distiller(palette = "Paired", direction = 1, limit=c(12,17))
```


openstreetmap已经无法使用了.
```{r, warning=FALSE, message=FALSE, fig.width=8, fig.height=8}
mbox <- c(left = 116, bottom = 39.6, right = 116.8, top = 40.2)
map <- get_openstreetmap(mbox)

ggmap(map) + 
  geom_point(data=obs, mapping = aes(x=lon, y=lat, col=temp, size=2))+
  scale_color_distiller(palette = "Paired", direction = 1, limit=c(12,17))
```